# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default aliases and functions
source ~/.local/share/omarchy/default/bash/rc

